name: 'github-labeler'
description: 'Declarative way to configure GitHub labels'
inputs:
  config:
    description: 'Path to YAML file which defines GitHub labels'
    required: false
    default: '.github/labels.yml'
  import:
    description: 'Import existing labels if enabled'
    required: false
    default: 'false'
  dryrun:
    description: 'Just show what would be done if enabled'
    required: false
    default: 'false'
outputs:
  result:
    description: 'Outputs of github-labeler command'
runs:
  using: 'docker'
  image: 'Dockerfile'
